### ISSUE TITLE
Tesseract 4

### ISSUE THREAD

**Issue by ionspicica** [Exteris/tesseract-mrz#1]
Hi! Traineddata can be used with tesseract 4?

**Comment by DaanVanVugt** [comment]
I don't see why not. I haven't tried it though.

**Comment by ionspicica** [comment]
I ask because for tesseract 4 is applied other technology for training and i don’t now exactly if your trainneddata will work with tesseract 4

**Comment by DaanVanVugt** [comment]
Ah yes, I see.
From https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00
> For 4.00 at least, the old recognition engine is still present, and can also be trained, but is deprecated, and, unless good reasons materialize to keep it, may be deleted in a future release.

So it will work (by using the old engine).
> Compatibility with Tesseract 3 is enabled by using the Legacy OCR Engine mode (--oem 0). It also needs traineddata files which support the legacy engine, for example those from the tessdata repository.

I think using the tesseract 4 preprovided training should also work, without specifically training on this font. It might be slower on mobile (since the cpu usage is much higher but is mitigated by AVX2 and openMP usage)
